### ISSUE TITLE
uTools 插件问题

### ISSUE THREAD

**Issue by Undeio** [lion1ou/calendar#2]
#### 1. 定位不对，身处北京，定位杭州

<img width="593" alt="图片" src="https://user-images.githubusercontent.com/40680527/119590543-8a57f200-be07-11eb-9dae-9fdd023440d2.png">

#### 2. 切换日期，农历不变，需要选择日期才会变

![test](https://user-images.githubusercontent.com/40680527/119590942-4addd580-be08-11eb-9379-accf62fbf774.gif)

**Comment by lion1ou** [comment]
好的，收到。 感谢反馈，会尽快增加功能，并修复bug

**Comment by lion1ou** [comment]
已修复
